-- Import Reddit Sources
-- Copy all 138 Reddit sources from CSV into the sources table

-- Format: INSERT INTO sources (name, url, country, enabled, type, created_at, updated_at) VALUES (...);

INSERT INTO sources (name, url, country, enabled, type, created_at, updated_at) VALUES
('Reddit - r/travel', 'https://www.reddit.com/r/travel/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/solotravel', 'https://www.reddit.com/r/solotravel/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/worldnews', 'https://www.reddit.com/r/worldnews/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/news', 'https://www.reddit.com/r/news/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/disasters', 'https://www.reddit.com/r/disasters/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/geopolitics', 'https://www.reddit.com/r/geopolitics/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/ukraine', 'https://www.reddit.com/r/ukraine/.rss', 'Ukraine', true, 'reddit', now(), now()),
('Reddit - r/russia', 'https://www.reddit.com/r/russia/.rss', 'Russia', true, 'reddit', now(), now()),
('Reddit - r/turkey', 'https://www.reddit.com/r/turkey/.rss', 'Turkey', true, 'reddit', now(), now()),
('Reddit - r/armenia', 'https://www.reddit.com/r/armenia/.rss', 'Armenia', true, 'reddit', now(), now()),
('Reddit - r/europe', 'https://www.reddit.com/r/europe/.rss', 'Europe', true, 'reddit', now(), now()),
('Reddit - r/UK', 'https://www.reddit.com/r/unitedkingdom/.rss', 'United Kingdom', true, 'reddit', now(), now()),
('Reddit - r/France', 'https://www.reddit.com/r/france/.rss', 'France', true, 'reddit', now(), now()),
('Reddit - r/Germany', 'https://www.reddit.com/r/de/.rss', 'Germany', true, 'reddit', now(), now()),
('Reddit - r/Italy', 'https://www.reddit.com/r/italy/.rss', 'Italy', true, 'reddit', now(), now()),
('Reddit - r/Spain', 'https://www.reddit.com/r/spain/.rss', 'Spain', true, 'reddit', now(), now()),
('Reddit - r/Barcelona', 'https://www.reddit.com/r/Barcelona/.rss', 'Spain', true, 'reddit', now(), now()),
('Reddit - r/Portugal', 'https://www.reddit.com/r/portugal/.rss', 'Portugal', true, 'reddit', now(), now()),
('Reddit - r/Greece', 'https://www.reddit.com/r/greece/.rss', 'Greece', true, 'reddit', now(), now()),
('Reddit - r/Netherlands', 'https://www.reddit.com/r/Netherlands/.rss', 'Netherlands', true, 'reddit', now(), now()),
('Reddit - r/Belgium', 'https://www.reddit.com/r/Belgium/.rss', 'Belgium', true, 'reddit', now(), now()),
('Reddit - r/Switzerland', 'https://www.reddit.com/r/Switzerland/.rss', 'Switzerland', true, 'reddit', now(), now()),
('Reddit - r/Austria', 'https://www.reddit.com/r/Austria/.rss', 'Austria', true, 'reddit', now(), now()),
('Reddit - r/Poland', 'https://www.reddit.com/r/Poland/.rss', 'Poland', true, 'reddit', now(), now()),
('Reddit - r/Romania', 'https://www.reddit.com/r/Romania/.rss', 'Romania', true, 'reddit', now(), now()),
('Reddit - r/Hungary', 'https://www.reddit.com/r/Hungary/.rss', 'Hungary', true, 'reddit', now(), now()),
('Reddit - r/CzechRepublic', 'https://www.reddit.com/r/czech/.rss', 'Czech Republic', true, 'reddit', now(), now()),
('Reddit - r/Sweden', 'https://www.reddit.com/r/sweden/.rss', 'Sweden', true, 'reddit', now(), now()),
('Reddit - r/Norway', 'https://www.reddit.com/r/Norway/.rss', 'Norway', true, 'reddit', now(), now()),
('Reddit - r/Denmark', 'https://www.reddit.com/r/Denmark/.rss', 'Denmark', true, 'reddit', now(), now()),
('Reddit - r/Finland', 'https://www.reddit.com/r/Finland/.rss', 'Finland', true, 'reddit', now(), now()),
('Reddit - r/Ireland', 'https://www.reddit.com/r/ireland/.rss', 'Ireland', true, 'reddit', now(), now()),
('Reddit - r/Mexico', 'https://www.reddit.com/r/mexico/.rss', 'Mexico', true, 'reddit', now(), now()),
('Reddit - r/Guatemala', 'https://www.reddit.com/r/Guatemala/.rss', 'Guatemala', true, 'reddit', now(), now()),
('Reddit - r/CostaRica', 'https://www.reddit.com/r/costarica/.rss', 'Costa Rica', true, 'reddit', now(), now()),
('Reddit - r/Panama', 'https://www.reddit.com/r/Panama/.rss', 'Panama', true, 'reddit', now(), now()),
('Reddit - r/Colombia', 'https://www.reddit.com/r/Colombia/.rss', 'Colombia', true, 'reddit', now(), now()),
('Reddit - r/Venezuela', 'https://www.reddit.com/r/Venezuela/.rss', 'Venezuela', true, 'reddit', now(), now()),
('Reddit - r/Ecuador', 'https://www.reddit.com/r/Ecuador/.rss', 'Ecuador', true, 'reddit', now(), now()),
('Reddit - r/Peru', 'https://www.reddit.com/r/Peru/.rss', 'Peru', true, 'reddit', now(), now()),
('Reddit - r/Brazil', 'https://www.reddit.com/r/brazil/.rss', 'Brazil', true, 'reddit', now(), now()),
('Reddit - r/Chile', 'https://www.reddit.com/r/chile/.rss', 'Chile', true, 'reddit', now(), now()),
('Reddit - r/Argentina', 'https://www.reddit.com/r/Argentina/.rss', 'Argentina', true, 'reddit', now(), now()),
('Reddit - r/Bolivia', 'https://www.reddit.com/r/Bolivia/.rss', 'Bolivia', true, 'reddit', now(), now()),
('Reddit - r/Paraguay', 'https://www.reddit.com/r/Paraguay/.rss', 'Paraguay', true, 'reddit', now(), now()),
('Reddit - r/Uruguay', 'https://www.reddit.com/r/Uruguay/.rss', 'Uruguay', true, 'reddit', now(), now()),
('Reddit - r/Canada', 'https://www.reddit.com/r/canada/.rss', 'Canada', true, 'reddit', now(), now()),
('Reddit - r/Toronto', 'https://www.reddit.com/r/toronto/.rss', 'Canada', true, 'reddit', now(), now()),
('Reddit - r/Vancouver', 'https://www.reddit.com/r/vancouver/.rss', 'Canada', true, 'reddit', now(), now()),
('Reddit - r/USA', 'https://www.reddit.com/r/usa/.rss', 'United States', true, 'reddit', now(), now()),
('Reddit - r/NewYork', 'https://www.reddit.com/r/newyork/.rss', 'United States', true, 'reddit', now(), now()),
('Reddit - r/LosAngeles', 'https://www.reddit.com/r/losangeles/.rss', 'United States', true, 'reddit', now(), now()),
('Reddit - r/Miami', 'https://www.reddit.com/r/miami/.rss', 'United States', true, 'reddit', now(), now()),
('Reddit - r/Chicago', 'https://www.reddit.com/r/chicago/.rss', 'United States', true, 'reddit', now(), now()),
('Reddit - r/China', 'https://www.reddit.com/r/china/.rss', 'China', true, 'reddit', now(), now()),
('Reddit - r/Beijing', 'https://www.reddit.com/r/beijing/.rss', 'China', true, 'reddit', now(), now()),
('Reddit - r/Shanghai', 'https://www.reddit.com/r/shanghai/.rss', 'China', true, 'reddit', now(), now()),
('Reddit - r/HongKong', 'https://www.reddit.com/r/hongkong/.rss', 'Hong Kong', true, 'reddit', now(), now()),
('Reddit - r/Taiwan', 'https://www.reddit.com/r/taiwan/.rss', 'Taiwan', true, 'reddit', now(), now()),
('Reddit - r/Japan', 'https://www.reddit.com/r/japan/.rss', 'Japan', true, 'reddit', now(), now()),
('Reddit - r/Tokyo', 'https://www.reddit.com/r/tokyo/.rss', 'Japan', true, 'reddit', now(), now()),
('Reddit - r/SouthKorea', 'https://www.reddit.com/r/korea/.rss', 'South Korea', true, 'reddit', now(), now()),
('Reddit - r/NorthKorea', 'https://www.reddit.com/r/northkorea/.rss', 'North Korea', true, 'reddit', now(), now()),
('Reddit - r/Thailand', 'https://www.reddit.com/r/thailand/.rss', 'Thailand', true, 'reddit', now(), now()),
('Reddit - r/Bangkok', 'https://www.reddit.com/r/Bangkok/.rss', 'Thailand', true, 'reddit', now(), now()),
('Reddit - r/Vietnam', 'https://www.reddit.com/r/vietnam/.rss', 'Vietnam', true, 'reddit', now(), now()),
('Reddit - r/Philippines', 'https://www.reddit.com/r/Philippines/.rss', 'Philippines', true, 'reddit', now(), now()),
('Reddit - r/Indonesia', 'https://www.reddit.com/r/indonesia/.rss', 'Indonesia', true, 'reddit', now(), now()),
('Reddit - r/Malaysia', 'https://www.reddit.com/r/malaysia/.rss', 'Malaysia', true, 'reddit', now(), now()),
('Reddit - r/Singapore', 'https://www.reddit.com/r/singapore/.rss', 'Singapore', true, 'reddit', now(), now()),
('Reddit - r/India', 'https://www.reddit.com/r/india/.rss', 'India', true, 'reddit', now(), now()),
('Reddit - r/Delhi', 'https://www.reddit.com/r/delhi/.rss', 'India', true, 'reddit', now(), now()),
('Reddit - r/Mumbai', 'https://www.reddit.com/r/mumbai/.rss', 'India', true, 'reddit', now(), now()),
('Reddit - r/Pakistan', 'https://www.reddit.com/r/pakistan/.rss', 'Pakistan', true, 'reddit', now(), now()),
('Reddit - r/Bangladesh', 'https://www.reddit.com/r/bangladesh/.rss', 'Bangladesh', true, 'reddit', now(), now()),
('Reddit - r/SriLanka', 'https://www.reddit.com/r/srilanka/.rss', 'Sri Lanka', true, 'reddit', now(), now()),
('Reddit - r/Nepal', 'https://www.reddit.com/r/nepal/.rss', 'Nepal', true, 'reddit', now(), now()),
('Reddit - r/Afghanistan', 'https://www.reddit.com/r/afghanistan/.rss', 'Afghanistan', true, 'reddit', now(), now()),
('Reddit - r/Iran', 'https://www.reddit.com/r/iran/.rss', 'Iran', true, 'reddit', now(), now()),
('Reddit - r/Iraq', 'https://www.reddit.com/r/iraq/.rss', 'Iraq', true, 'reddit', now(), now()),
('Reddit - r/Syria', 'https://www.reddit.com/r/syriancivilwar/.rss', 'Syria', true, 'reddit', now(), now()),
('Reddit - r/Lebanon', 'https://www.reddit.com/r/lebanon/.rss', 'Lebanon', true, 'reddit', now(), now()),
('Reddit - r/Jordan', 'https://www.reddit.com/r/jordan/.rss', 'Jordan', true, 'reddit', now(), now()),
('Reddit - r/Israel', 'https://www.reddit.com/r/israel/.rss', 'Israel', true, 'reddit', now(), now()),
('Reddit - r/Palestine', 'https://www.reddit.com/r/palestine/.rss', 'Palestine', true, 'reddit', now(), now()),
('Reddit - r/SaudiArabia', 'https://www.reddit.com/r/saudiarabia/.rss', 'Saudi Arabia', true, 'reddit', now(), now()),
('Reddit - r/UAE', 'https://www.reddit.com/r/UAE/.rss', 'United Arab Emirates', true, 'reddit', now(), now()),
('Reddit - r/Egypt', 'https://www.reddit.com/r/egypt/.rss', 'Egypt', true, 'reddit', now(), now()),
('Reddit - r/Morocco', 'https://www.reddit.com/r/morocco/.rss', 'Morocco', true, 'reddit', now(), now()),
('Reddit - r/Algeria', 'https://www.reddit.com/r/algeria/.rss', 'Algeria', true, 'reddit', now(), now()),
('Reddit - r/Tunisia', 'https://www.reddit.com/r/tunisia/.rss', 'Tunisia', true, 'reddit', now(), now()),
('Reddit - r/Libya', 'https://www.reddit.com/r/libya/.rss', 'Libya', true, 'reddit', now(), now()),
('Reddit - r/SouthAfrica', 'https://www.reddit.com/r/southafrica/.rss', 'South Africa', true, 'reddit', now(), now()),
('Reddit - r/Nigeria', 'https://www.reddit.com/r/Nigeria/.rss', 'Nigeria', true, 'reddit', now(), now()),
('Reddit - r/Kenya', 'https://www.reddit.com/r/kenya/.rss', 'Kenya', true, 'reddit', now(), now()),
('Reddit - r/Ethiopia', 'https://www.reddit.com/r/ethiopia/.rss', 'Ethiopia', true, 'reddit', now(), now()),
('Reddit - r/Somalia', 'https://www.reddit.com/r/somalia/.rss', 'Somalia', true, 'reddit', now(), now()),
('Reddit - r/Australia', 'https://www.reddit.com/r/australia/.rss', 'Australia', true, 'reddit', now(), now()),
('Reddit - r/Sydney', 'https://www.reddit.com/r/sydney/.rss', 'Australia', true, 'reddit', now(), now()),
('Reddit - r/Melbourne', 'https://www.reddit.com/r/melbourne/.rss', 'Australia', true, 'reddit', now(), now()),
('Reddit - r/NewZealand', 'https://www.reddit.com/r/newzealand/.rss', 'New Zealand', true, 'reddit', now(), now()),
('Reddit - r/aviation', 'https://www.reddit.com/r/aviation/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/AirCrashInvestigation', 'https://www.reddit.com/r/aircrashes/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/Coronavirus', 'https://www.reddit.com/r/coronavirus/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/COVID19', 'https://www.reddit.com/r/COVID19/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/Epidemiology', 'https://www.reddit.com/r/epidemiology/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/PublicHealth', 'https://www.reddit.com/r/publichealth/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/TrueCrime', 'https://www.reddit.com/r/TrueCrime/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/weather', 'https://www.reddit.com/r/weather/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/TropicalWeather', 'https://www.reddit.com/r/TropicalWeather/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/Earthquake', 'https://www.reddit.com/r/earthquakes/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/volcanoes', 'https://www.reddit.com/r/volcanoes/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/environment', 'https://www.reddit.com/r/environment/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/climate', 'https://www.reddit.com/r/climate/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/wildfire', 'https://www.reddit.com/r/wildfire/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/PrepperIntel', 'https://www.reddit.com/r/PrepperIntel/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/collapse', 'https://www.reddit.com/r/collapse/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/ConflictNews', 'https://www.reddit.com/r/ConflictNews/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/syriancivilwar', 'https://www.reddit.com/r/syriancivilwar/.rss', 'Global', true, 'reddit', now(), now()),
('Reddit - r/YemeniCrisis', 'https://www.reddit.com/r/YemeniCrisis/.rss', 'Global', true, 'reddit', now(), now());

-- Verify import
SELECT COUNT(*) as total_reddit_sources FROM sources WHERE type = 'reddit';
