import { useScour } from "./ScourContext";
import React, { useEffect, useState } from "react";
import GeoJsonPreview from "./GeoJsonPreview";

/* =========================
   Types
========================= */

export type PermissionSet = {
  canReview: boolean;
  canScour: boolean;
  canApproveAndPost: boolean;
  canDismiss: boolean;
  canDelete: boolean;
  canEditAlerts: boolean;
};

type Props = {
  permissions: PermissionSet;
};

export interface Alert {
  id: string;
  title: string;
  summary: string;
  recommendations?: string;

  location: string;
  country: string;
  region?: string;

  event_type?: string;
  severity: "critical" | "warning" | "caution" | "informative";
  status: string;

  source_url?: string;
  article_url?: string;
  sources?: string;

  event_start_date?: string;
  event_end_date?: string;

  geojson?: any;

  ai_generated?: boolean;
  created_at: string;
}

/* =========================
   Config
========================= */

import { getApiUrl } from "../lib/supabase/api";

const API_BASE = getApiUrl("");

const SEVERITY_META: Record<
  Alert["severity"],
  { emoji: string; label: string; color: string }
> = {
  critical: { emoji: "", label: "CRITICAL", color: "bg-red-600" },
  warning: { emoji: "", label: "WARNING", color: "bg-orange-500" },
  caution: { emoji: "", label: "CAUTION", color: "bg-yellow-500" },
  informative: { emoji: "", label: "INFO", color: "bg-blue-500" },
};

function formatDateRange(a: Alert) {
  const start = a.event_start_date || "";
  const end = a.event_end_date || "";
  if (start && end) return `${start}  ${end}`;
  if (start && !end) return `${start} (ongoing)`;
  if (!start && end) return `until ${end}`;
  return "Ongoing";
}

function whatsappTemplate(a: Alert) {
  const s = SEVERITY_META[a.severity];
  const topic = (a.event_type || "General").trim();
  const sources = a.article_url || a.source_url || "";

  return `🚨 *TRAVEL ALERT* 🚨

*Severity:* ${s.label}
*Location:* ${a.location}, ${a.country}
${a.region ? `*Region:* ${a.region}\n` : ''}*Event Type:* ${topic}
*Timeline:* ${formatDateRange(a)}

*Details:*
${a.summary}

${a.recommendations ? `*Recommended Actions:*\n${a.recommendations}\n\n` : ''}*Sources:*
${sources || "Internal Intelligence"}

━━━━━━━━━━━━━━━━━━━━
Generated by MAGNUS Alert System
`.trim();
}

/* =========================
   Component
========================= */

export default function AlertReviewQueueInline({ permissions }: Props) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [editing, setEditing] = useState<Record<string, boolean>>({});
  const [drafts, setDrafts] = useState<Record<string, Partial<Alert>>>({});
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (permissions.canReview) void loadAlerts();
  }, [permissions.canReview]);

  async function loadAlerts() {
    try {
      setLoading(true);
      setError(null);
      const res = await fetch(`${API_BASE}/alerts/review`);
      if (!res.ok) throw new Error(`Failed to load alerts (${res.status})`);
      const data = await res.json();
      setAlerts(Array.isArray(data.alerts) ? data.alerts : []);
    } catch (e: any) {
      setError(e?.message || "Failed to load alerts");
    } finally {
      setLoading(false);
    }
  }

  function startEdit(a: Alert) {
    setEditing((e) => ({ ...e, [a.id]: true }));
    setDrafts((ds) => ({ ...ds, [a.id]: { ...a } }));
  }

  function cancelEdit(id: string) {
    setEditing((e) => ({ ...e, [id]: false }));
  }

  async function saveEdit(id: string) {
    const patch = drafts[id];
    if (!patch) return;

    await fetch(`${API_BASE}/alerts/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    });

    setAlerts((a) => a.map((x) => (x.id === id ? { ...x, ...patch } : x)));
    setEditing((e) => ({ ...e, [id]: false }));
  }

  async function approve(id: string) {
    await fetch(`${API_BASE}/alerts/${id}/approve`, { method: "POST" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function dismiss(id: string) {
    await fetch(`${API_BASE}/alerts/${id}/dismiss`, { method: "POST" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function del(id: string) {
    if (!window.confirm("Delete alert permanently?")) return;
    await fetch(`${API_BASE}/alerts/${id}`, { method: "DELETE" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function batchDismiss() {
    if (!selected.size) return;
    if (!window.confirm(`Dismiss ${selected.size} alerts?`)) return;

    await Promise.all(
      [...selected].map((id) =>
        fetch(`${API_BASE}/alerts/${id}/dismiss`, { method: "POST" })
      )
    );

    setAlerts((a) => a.filter((x) => !selected.has(x.id)));
    setSelected(new Set());
  }

  async function batchDelete() {
    if (!selected.size) return;
    if (!window.confirm(`DELETE ${selected.size} alerts?`)) return;

    await Promise.all(
      [...selected].map((id) =>
        fetch(`${API_BASE}/alerts/${id}`, { method: "DELETE" })
      )
    );

    setAlerts((a) => a.filter((x) => !selected.has(x.id)));
    setSelected(new Set());
  }

  if (!permissions.canReview) {
    return <div className="p-4 text-gray-500">No review permissions</div>;
  }

  if (loading) return <div className="p-6">Loading alerts</div>;

  if (error) {
    return (
      <div className="p-4 border border-red-300 bg-red-50 rounded">
        <div className="text-red-700 mb-2">{error}</div>
        <button
          className="px-3 py-1 bg-red-600 text-white rounded"
          onClick={() => void loadAlerts()}
        >
          Retry
        </button>
      </div>
    );
  }



const { startScour, isScouring, accessToken } = useScour() as any;

return (
  <div className="space-y-4">
    {/* Run Scour (context-driven, single trigger) */}
    {permissions.canScour && (
      <div className="flex justify-end mb-3">
        <button
          onClick={() => startScour(accessToken)}
          disabled={isScouring}
          className={`px-4 py-2 rounded text-white ${
            isScouring ? "bg-gray-400 cursor-not-allowed" : "bg-indigo-600"
          }`}
        >
          {isScouring ? "Scouring…" : "Run Scour"}
        </button>
      </div>
    )}

    {/* Batch actions */}
    {selected.size > 0 && (
      <div className="sticky top-0 z-10 p-3 bg-gray-50 border rounded flex gap-3">
        <strong>{selected.size} selected</strong>

        <button
          onClick={batchDismiss}
          className="bg-yellow-600 text-white px-3 py-1 rounded"
        >
          Batch Dismiss
        </button>

        <button
          onClick={batchDelete}
          className="bg-red-600 text-white px-3 py-1 rounded"
        >
          Batch Delete
        </button>
      </div>
    )}

    {/* Alerts */}
    {alerts.map((a) => {
      const meta = SEVERITY_META[a.severity];
      const open = !!expanded[a.id];
      const edit = !!editing[a.id];
      const d = (drafts[a.id] || a) as Alert;

      return (
        <div key={a.id} className="border-2 rounded-lg bg-white shadow-md overflow-hidden">
          {/* Header - Always Visible */}
          <div className="bg-gradient-to-r from-gray-50 to-gray-100 p-4 border-b-2">
            <div className="flex items-start justify-between gap-4 mb-3">
              <div className="flex items-start gap-3 flex-1">
                <input
                  type="checkbox"
                  checked={selected.has(a.id)}
                  onChange={() =>
                    setSelected((s) => {
                      const n = new Set(s);
                      n.has(a.id) ? n.delete(a.id) : n.add(a.id);
                      return n;
                    })
                  }
                  className="mt-1"
                />
                <div className="flex-1">
                  <h3 className="text-lg font-bold text-gray-900 mb-2">{a.title}</h3>
                  <div className="flex gap-2 items-center flex-wrap">
                    <span className={`text-sm text-white font-semibold px-3 py-1 rounded-full ${meta.color}`}>
                      {meta.emoji} {meta.label}
                    </span>
                    <span className="text-sm font-medium text-gray-700">📍 {a.location}, {a.country}</span>
                    <span className="text-sm text-gray-600">🕐 {formatDateRange(a)}</span>
                  </div>
                </div>
              </div>
              <button
                className="text-sm font-semibold text-indigo-600 hover:text-indigo-800 whitespace-nowrap"
                onClick={() =>
                  setExpanded((e) => ({ ...e, [a.id]: !open }))
                }
              >
                {open ? "▼ Collapse" : "▶ Expand"}
              </button>
            </div>

            {/* Summary - Always Visible */}
            <div className="text-gray-700 text-sm leading-relaxed mb-4">
              {a.summary}
            </div>

            {/* Quick Actions - Always Visible */}
            <div className="flex gap-2 flex-wrap">
              {permissions.canApproveAndPost && (
                <button
                  onClick={() => approve(a.id)}
                  className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded font-semibold text-sm transition"
                >
                  ✓ Approve & Post
                </button>
              )}

              {permissions.canDismiss && (
                <button
                  onClick={() => dismiss(a.id)}
                  className="bg-yellow-600 hover:bg-yellow-700 text-white px-4 py-2 rounded font-semibold text-sm transition"
                >
                  ⊘ Dismiss
                </button>
              )}

              <button
                onClick={() => {
                  navigator.clipboard.writeText(whatsappTemplate(a));
                  window.alert("✓ Copied WhatsApp alert");
                }}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded font-semibold text-sm transition"
              >
                💬 Copy WhatsApp
              </button>

              {permissions.canDelete && (
                <button
                  onClick={() => del(a.id)}
                  className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded font-semibold text-sm transition"
                >
                  🗑 Delete
                </button>
              )}
            </div>
          </div>

          {/* Expanded Content */}
          {open && (
            <div className="p-6 space-y-4 bg-white">
              {a.region && (
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Region</h4>
                  <p className="text-gray-700">{a.region}</p>
                </div>
              )}

              {a.event_type && (
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Event Type</h4>
                  <p className="text-gray-700">{a.event_type}</p>
                </div>
              )}

              {a.recommendations && (
                <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded">
                  <h4 className="font-semibold text-gray-900 mb-2">🎯 Traveler Recommendations</h4>
                  <p className="text-gray-700 whitespace-pre-wrap">{a.recommendations}</p>
                </div>
              )}

              {(a.source_url || a.article_url) && (
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Sources</h4>
                  <div className="space-y-1">
                    {a.sources && <p className="text-gray-700">Source: {a.sources}</p>}
                    {a.article_url && (
                      <a
                        href={a.article_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline block"
                      >
                        📄 Article Link
                      </a>
                    )}
                    {a.source_url && (
                      <a
                        href={a.source_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline block"
                      >
                        🔗 Source Link
                      </a>
                    )}
                  </div>
                </div>
              )}

              {a.geojson && (
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Map</h4>
                  <GeoJsonPreview geojson={a.geojson} />
                </div>
              )}

              <div className="text-xs text-gray-500 pt-4 border-t">
                Created: {new Date(a.created_at).toLocaleString()}
              </div>
            </div>
          )}
        </div>
      );
    })}
  </div>
);


}


