import { useScour } from "./ScourContext";
import React, { useEffect, useState } from "react";
import GeoJsonPreview from "./GeoJsonPreview";
import MAGNUS_COLORS from "../styles/magnus-colors";

/* =========================
   Types
========================= */

export type PermissionSet = {
  canReview: boolean;
  canScour: boolean;
  canApproveAndPost: boolean;
  canDismiss: boolean;
  canDelete: boolean;
  canEditAlerts: boolean;
};

type Props = {
  permissions: PermissionSet;
};

export interface Alert {
  id: string;
  title: string;
  summary: string;
  recommendations?: string;

  location: string;
  country: string;
  region?: string;

  event_type?: string;
  severity: "critical" | "warning" | "caution" | "informative";
  status: string;

  source_url?: string;
  article_url?: string;
  sources?: string;

  event_start_date?: string;
  event_end_date?: string;

  geojson?: any;

  ai_generated?: boolean;
  created_at: string;
}

/* =========================
   Config
========================= */

import { getApiUrl } from "../lib/supabase/api";

const API_BASE = getApiUrl("");

const SEVERITY_META: Record<
  Alert["severity"],
  { emoji: string; label: string; color: string; bgColor?: string }
> = {
  critical: { emoji: "", label: "CRITICAL", color: "text-white px-3 py-1 rounded-full font-semibold", bgColor: MAGNUS_COLORS.critical },
  warning: { emoji: "", label: "WARNING", color: "text-white px-3 py-1 rounded-full font-semibold", bgColor: MAGNUS_COLORS.warning },
  caution: { emoji: "", label: "CAUTION", color: "text-white px-3 py-1 rounded-full font-semibold", bgColor: MAGNUS_COLORS.caution },
  informative: { emoji: "", label: "INFO", color: "text-white px-3 py-1 rounded-full font-semibold", bgColor: MAGNUS_COLORS.informative },
};

function formatEventTime(a: Alert) {
  if (!a.event_start_date) return "Date not specified";
  
  const start = new Date(a.event_start_date);
  const formatted = start.toLocaleString('en-US', { 
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });
  
  return formatted;
}

function formatDateRange(a: Alert) {
  // Format event dates
  const start = a.event_start_date || "";
  const end = a.event_end_date || "";
  let eventDates = "Ongoing";
  if (start && end) eventDates = `${new Date(start).toLocaleString()} to ${new Date(end).toLocaleString()}`;
  else if (start && !end) eventDates = `${new Date(start).toLocaleString()} (ongoing)`;
  else if (!start && end) eventDates = `until ${new Date(end).toLocaleString()}`;
  
  // Format alert creation date
  const createdAt = a.created_at ? new Date(a.created_at).toLocaleString() : "Unknown";
  
  return `Event: ${eventDates} | Alert Created: ${createdAt}`;
}

function whatsappTemplate(a: Alert) {
  const s = SEVERITY_META[a.severity];
  const topic = (a.event_type || "General").trim();
  const sources = a.article_url || a.source_url || "";

  return `🚨 *TRAVEL ALERT* 🚨

*Location:* ${a.location}, ${a.country}
*Severity:* ${s.label}
${a.region ? `*Region:* ${a.region}\n` : ''}*Event Type:* ${topic}
*Timeline:* ${formatDateRange(a)}

*Details:*
${a.summary}

${a.recommendations ? `*Recommended Actions:*\n${a.recommendations}\n\n` : ''}*Sources:*
${sources || "Internal Intelligence"}

━━━━━━━━━━━━━━━━━━━━
Generated by MAGNUS Alert System
`.trim();
}

/* =========================
   Component
========================= */

export default function AlertReviewQueueInline({ permissions }: Props) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [editing, setEditing] = useState<Record<string, boolean>>({});
  const [drafts, setDrafts] = useState<Record<string, Partial<Alert>>>({});
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!permissions.canReview) return;
    
    // Load immediately
    void loadAlerts();
    
    // Then poll every 3 seconds for new alerts during active session
    const interval = setInterval(() => {
      loadAlerts().catch(e => console.warn('Alert poll failed:', e));
    }, 3000);
    
    return () => clearInterval(interval);
  }, [permissions.canReview]);

  async function loadAlerts() {
    try {
      setLoading(false); // Don't show loading spinner on refresh, only on initial load
      setError(null);
      const res = await fetch(`${API_BASE}/alerts/review`);
      if (!res.ok) throw new Error(`Failed to load alerts (${res.status})`);
      const data = await res.json();
      setAlerts(Array.isArray(data.alerts) ? data.alerts : []);
    } catch (e: any) {
      setError(e?.message || "Failed to load alerts");
    }
  }

  function startEdit(a: Alert) {
    setEditing((e) => ({ ...e, [a.id]: true }));
    setDrafts((ds) => ({ ...ds, [a.id]: { ...a } }));
  }

  function cancelEdit(id: string) {
    setEditing((e) => ({ ...e, [id]: false }));
  }

  async function saveEdit(id: string) {
    const patch = drafts[id];
    if (!patch) return;

    await fetch(`${API_BASE}/alerts/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    });

    setAlerts((a) => a.map((x) => (x.id === id ? { ...x, ...patch } : x)));
    setEditing((e) => ({ ...e, [id]: false }));
  }

  async function approve(id: string) {
    await fetch(`${API_BASE}/alerts/${id}/approve`, { method: "POST" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function dismiss(id: string) {
    await fetch(`${API_BASE}/alerts/${id}/dismiss`, { method: "POST" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function del(id: string) {
    if (!window.confirm("Delete alert permanently?")) return;
    await fetch(`${API_BASE}/alerts/${id}`, { method: "DELETE" });
    setAlerts((a) => a.filter((x) => x.id !== id));
  }

  async function batchDismiss() {
    if (!selected.size) return;
    if (!window.confirm(`Dismiss ${selected.size} alerts?`)) return;

    await Promise.all(
      [...selected].map((id) =>
        fetch(`${API_BASE}/alerts/${id}/dismiss`, { method: "POST" })
      )
    );

    setAlerts((a) => a.filter((x) => !selected.has(x.id)));
    setSelected(new Set());
  }

  async function batchDelete() {
    if (!selected.size) return;
    if (!window.confirm(`DELETE ${selected.size} alerts?`)) return;

    await Promise.all(
      [...selected].map((id) =>
        fetch(`${API_BASE}/alerts/${id}`, { method: "DELETE" })
      )
    );

    setAlerts((a) => a.filter((x) => !selected.has(x.id)));
    setSelected(new Set());
  }

  if (!permissions.canReview) {
    return <div className="p-4" style={{ color: MAGNUS_COLORS.secondaryText }}>No review permissions</div>;
  }

  if (loading) return <div className="p-6">Loading alerts</div>;

  if (error) {
    return (
      <div className="p-4 border rounded" style={{ borderColor: MAGNUS_COLORS.critical, backgroundColor: MAGNUS_COLORS.offWhite }}>
        <div className="mb-2" style={{ color: MAGNUS_COLORS.critical }}>{error}</div>
        <button
          className="px-3 py-1 text-white rounded font-semibold transition hover:opacity-90"
          style={{ backgroundColor: MAGNUS_COLORS.critical }}
          onClick={() => void loadAlerts()}
        >
          Retry
        </button>
      </div>
    );
  }



const { startScour, isScouring, accessToken } = useScour() as any;

return (
  <div className="space-y-4">
    {/* Run Scour (context-driven, single trigger) */}
    {permissions.canScour && (
      <div className="flex justify-end mb-3">
        <button
          onClick={() => startScour(accessToken)}
          disabled={isScouring}
          className="px-4 py-2 rounded text-white font-semibold transition disabled:opacity-60"
          style={{ backgroundColor: isScouring ? MAGNUS_COLORS.border : MAGNUS_COLORS.darkGreen }}
        >
          {isScouring ? "Scouring…" : "Run Scour"}
        </button>
      </div>
    )}

    {/* Batch actions */}
    {selected.size > 0 && (
      <div className="sticky top-0 z-10 p-3 border rounded flex gap-3" style={{ backgroundColor: MAGNUS_COLORS.offWhite }}>
        <strong style={{ color: MAGNUS_COLORS.darkGreen }}>{selected.size} selected</strong>

        <button
          onClick={batchDismiss}
          className="text-white px-3 py-1 rounded font-semibold transition hover:opacity-90"
          style={{ backgroundColor: MAGNUS_COLORS.orange }}
        >
          Batch Dismiss
        </button>

        <button
          onClick={batchDelete}
          className="text-white px-3 py-1 rounded font-semibold transition hover:opacity-90"
          style={{ backgroundColor: MAGNUS_COLORS.critical }}
        >
          Batch Delete
        </button>
      </div>
    )}

    {/* Alerts */}
    {alerts.map((a) => {
      const meta = SEVERITY_META[a.severity];
      const open = !!expanded[a.id];
      const edit = !!editing[a.id];
      const d = (drafts[a.id] || a) as Alert;

      return (
        <div key={a.id} className="border-2 rounded-lg bg-white shadow-md overflow-hidden" style={{ borderColor: MAGNUS_COLORS.border }}>
          {/* Header - Always Visible */}
          <div className="p-4 border-b-2" style={{ backgroundColor: MAGNUS_COLORS.offWhite, borderBottomColor: MAGNUS_COLORS.deepGreen }}>
            <div className="flex items-start justify-between gap-4 mb-3">
              <div className="flex items-start gap-3 flex-1">
                <input
                  type="checkbox"
                  checked={selected.has(a.id)}
                  onChange={() =>
                    setSelected((s) => {
                      const n = new Set(s);
                      n.has(a.id) ? n.delete(a.id) : n.add(a.id);
                      return n;
                    })
                  }
                  className="mt-1"
                />
                <div className="flex-1">
                  <h3 className="text-lg font-bold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>{a.title}</h3>
                  <div className="flex gap-2 items-center flex-wrap">
                  <span
                    className={`text-sm font-semibold px-3 py-1 rounded-full ${meta.color}`}
                    style={{ backgroundColor: meta.bgColor }}
                  >
                    {meta.emoji} {meta.label}
                  </span>
                  <span className="text-sm font-medium" style={{ color: MAGNUS_COLORS.secondaryText }}>📍 {a.location}, {a.country}</span>
                  <span className="text-sm" style={{ color: MAGNUS_COLORS.secondaryText }}>🕐 {formatDateRange(a)}</span>
                  </div>
                </div>
              </div>
              <button
                className="text-sm font-semibold whitespace-nowrap hover:opacity-80 transition"
                style={{ color: MAGNUS_COLORS.deepGreen }}
                onClick={() =>
                  setExpanded((e) => ({ ...e, [a.id]: !open }))
                }
              >
                {open ? "▼ Collapse" : "▶ Expand"}
              </button>
            </div>

            {/* Summary - Always Visible */}
            <div className="text-sm leading-relaxed mb-4" style={{ color: MAGNUS_COLORS.secondaryText }}>
              {a.summary}
            </div>

            {/* Quick Actions - Always Visible */}
            <div className="flex gap-2 flex-wrap">
              {permissions.canApproveAndPost && (
                <button
                  onClick={() => approve(a.id)}
                  className="text-white px-4 py-2 rounded font-semibold text-sm transition hover:opacity-90"
                  style={{ backgroundColor: MAGNUS_COLORS.deepGreen }}
                >
                  ✓ Approve & Post
                </button>
              )}

              {permissions.canDismiss && (
                <button
                  onClick={() => dismiss(a.id)}
                  className="text-white px-4 py-2 rounded font-semibold text-sm transition hover:opacity-90"
                  style={{ backgroundColor: MAGNUS_COLORS.orange }}
                >
                  ⊘ Dismiss
                </button>
              )}

              <button
                onClick={() => {
                  navigator.clipboard.writeText(whatsappTemplate(a));
                  window.alert("✓ Copied WhatsApp alert");
                }}
                className="text-white px-4 py-2 rounded font-semibold text-sm transition hover:opacity-90"
                style={{ backgroundColor: MAGNUS_COLORS.deepGreen }}
              >
                💬 Copy WhatsApp
              </button>

              {permissions.canDelete && (
                <button
                  onClick={() => del(a.id)}
                  className="text-white px-4 py-2 rounded font-semibold text-sm transition hover:opacity-90"
                  style={{ backgroundColor: MAGNUS_COLORS.critical }}
                >
                  🗑 Delete
                </button>
              )}
            </div>
          </div>

          {/* Expanded Content */}
          {open && (
            <div className="p-6 space-y-4 bg-white">
              {a.region && (
                <div>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>Region</h4>
                  <p style={{ color: MAGNUS_COLORS.secondaryText }}>{a.region}</p>
                </div>
              )}

              {a.geojson && (
                <div>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>📍 Map</h4>
                  <GeoJsonPreview geojson={a.geojson} />
                </div>
              )}

              {a.event_type && (
                <div>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>Event Type</h4>
                  <p style={{ color: MAGNUS_COLORS.secondaryText }}>{a.event_type}</p>
                </div>
              )}

              {a.recommendations && (
                <div className="p-4 rounded" style={{ backgroundColor: MAGNUS_COLORS.offWhite, borderLeft: `4px solid ${MAGNUS_COLORS.deepGreen}` }}>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>🎯 Traveler Recommendations</h4>
                  <p className="whitespace-pre-wrap" style={{ color: MAGNUS_COLORS.secondaryText }}>{a.recommendations}</p>
                </div>
              )}

              {(a.source_url || a.article_url) && (
                <div>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>Sources</h4>
                  <div className="space-y-1">
                    {a.sources && <p style={{ color: MAGNUS_COLORS.secondaryText }}>Source: {a.sources}</p>}
                    {a.article_url && (
                      <a
                        href={a.article_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:underline block"
                        style={{ color: MAGNUS_COLORS.deepGreen }}
                      >
                        📄 Article Link
                      </a>
                    )}
                    {a.source_url && (
                      <a
                        href={a.source_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:underline block"
                        style={{ color: MAGNUS_COLORS.deepGreen }}
                      >
                        🔗 Source Link
                      </a>
                    )}
                  </div>
                </div>
              )}

              {a.geojson && (
                <div>
                  <h4 className="font-semibold mb-2" style={{ color: MAGNUS_COLORS.darkGreen }}>Map</h4>
                  <GeoJsonPreview geojson={a.geojson} />
                </div>
              )}

              {/* Internal Metadata - Not exported to WhatsApp/WordPress */}
              <div className="p-3 rounded border-l-4" style={{ backgroundColor: MAGNUS_COLORS.offWhite, borderLeftColor: MAGNUS_COLORS.secondaryText }}>
                <p className="text-xs font-semibold mb-2" style={{ color: MAGNUS_COLORS.secondaryText }}>⚙ Internal - Not Shared</p>
                <div className="space-y-1 text-sm">
                  <div style={{ color: MAGNUS_COLORS.secondaryText }}>
                    <span className="font-medium">Event Time:</span> {formatEventTime(a)}
                  </div>
                  <div style={{ color: MAGNUS_COLORS.secondaryText }}>
                    <span className="font-medium">Alert Created:</span> {new Date(a.created_at).toLocaleString()}
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t" style={{ color: MAGNUS_COLORS.tertiaryText, fontSize: "0.75rem" }}>
                ID: {a.id}
              </div>
            </div>
          )}
        </div>
      );
    })}
  </div>
);


}


