import React, { useEffect, useState } from "react";
import { apiFetchJson, apiPostJson } from "../lib/utils/api";

/* =========================
   Types
========================= */

export interface Trend {
  id: string;
  country: string;
  category: string;
  count: number;
  highest_severity: "critical" | "warning" | "caution" | "informative";
  last_seen_at: string;
  alert_ids?: string[];
}

export interface SituationalReport {
  id: string;
  trendId: string;
  title: string;
  country: string;
  severity: string;
  content: string;
  generatedAt: string;
  metadata: any;
}

/* =========================
   Helpers
========================= */

const SEVERITY_ORDER: Record<string, number> = {
  critical: 4,
  warning: 3,
  caution: 2,
  informative: 1,
};

const SEVERITY_COLOR: Record<string, string> = {
  critical: "bg-red-600",
  warning: "bg-orange-500",
  caution: "bg-yellow-500",
  informative: "bg-blue-500",
};

/* =========================
   Component
========================= */
export default function TrendsView({
  accessToken,
}: {
  accessToken?: string;
}) {
  const [trends, setTrends] = useState<Trend[]>([]);
  const [loading, setLoading] = useState(true);
  const [rebuilding, setRebuilding] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expandedTrendId, setExpandedTrendId] = useState<string | null>(null);
  const [generatingReport, setGeneratingReport] = useState<string | null>(null);
  const [report, setReport] = useState<SituationalReport | null>(null);

  const loadTrends = async () => {
    if (!accessToken) return;

    try {
      setLoading(true);
      setError(null);

      const res = await apiFetchJson<{ ok: boolean; trends?: Trend[] }>(
        "/trends",
        accessToken
      );

      if (!res?.ok) throw new Error("Failed to fetch trends");

      const sorted =
        (res.trends ?? [])
          .slice()
          .sort(
            (a, b) =>
              (SEVERITY_ORDER[b.highest_severity] ?? 0) -
              (SEVERITY_ORDER[a.highest_severity] ?? 0)
          );

      setTrends(sorted);
    } catch (e: any) {
      setError(e?.message || "Failed to load trends");
      setTrends([]);
    } finally {
      setLoading(false);
    }
  };

  const rebuildTrends = async () => {
    if (!accessToken) return;

    try {
      setLoading(true);
      setError(null);

      await apiFetchJson("/trends/rebuild", accessToken, {
        method: "POST",
      });

      await loadTrends();
    } catch (e: any) {
      setError(e?.message || "Failed to rebuild trends");
    } finally {
      setLoading(false);
    }
  };

  const generateReport = async (trendId: string) => {
    if (!accessToken) return;

    try {
      setGeneratingReport(trendId);
      setError(null);

      const res = await apiPostJson<{ ok: boolean; report?: SituationalReport; error?: string }>(
        `/trends/${trendId}/generate-report`,
        accessToken
      );

      if (!res?.ok || !res.report) {
        throw new Error(res?.error || "Failed to generate report");
      }

      setReport(res.report);
    } catch (e: any) {
      setError(e?.message || "Failed to generate report");
    } finally {
      setGeneratingReport(null);
    }
  };

  const exportReportAsText = () => {
    if (!report) return;

    const text = `
================================================================================
                    MAGNUS TRAVEL SAFETY INTELLIGENCE
                          SITUATIONAL REPORT
================================================================================

TITLE: ${report.title}
COUNTRY: ${report.country}
SEVERITY: ${report.severity.toUpperCase()}
GENERATED: ${new Date(report.generatedAt).toLocaleString()}

================================================================================

${report.content}

================================================================================
Report ID: ${report.id}
Trend ID: ${report.trendId}
Generated by MAGNUS Intelligence System
================================================================================
    `.trim();

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MAGNUS-Report-${report.country}-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  useEffect(() => {
    loadTrends();
  }, [accessToken]);

  if (loading) return <div className="p-4">Loading trends…</div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Trends</h2>

        <button
          onClick={rebuildTrends}
          disabled={rebuilding}
          className="px-3 py-1.5 text-sm rounded bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50"
        >
          {rebuilding ? "Rebuilding..." : "Rebuild Trends"}
        </button>
      </div>

      {error && <div className="text-red-600 text-sm">{error}</div>}

      {report && (
        <div className="border-l-4 border-indigo-600 bg-indigo-50 p-4 rounded shadow-md">
          <div className="flex items-start justify-between mb-3">
            <div>
              <h3 className="font-bold text-indigo-900">{report.title}</h3>
              <p className="text-xs text-indigo-700">
                Generated: {new Date(report.generatedAt).toLocaleString()}
              </p>
            </div>
            <button
              onClick={() => setReport(null)}
              className="text-indigo-600 hover:text-indigo-900 text-lg"
            >
              ✕
            </button>
          </div>
          <div className="bg-white p-3 rounded mb-3 text-sm text-gray-700 max-h-96 overflow-y-auto whitespace-pre-wrap">
            {report.content}
          </div>
          <button
            onClick={exportReportAsText}
            className="px-3 py-1.5 text-sm rounded bg-indigo-600 text-white hover:bg-indigo-700"
          >
            📥 Export as Text
          </button>
        </div>
      )}

      {!trends.length && (
        <div className="p-4 text-gray-500">
          No trends detected (≥ 3 alerts in last 14 days)
        </div>
      )}

      {trends.map((t) => (
        <div
          key={t.id}
          className="border rounded p-4 bg-white shadow-sm"
        >
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <div className="font-semibold">
                {t.country} — {t.category}
              </div>
              <div className="text-sm text-gray-600">
                {t.count} alerts · highest severity {t.highest_severity}
              </div>
              <div className="text-xs text-gray-400">
                Last seen: {new Date(t.last_seen_at).toLocaleString()}
              </div>
            </div>
            <button
              onClick={() => generateReport(t.id)}
              disabled={generatingReport === t.id}
              className="ml-3 px-3 py-1.5 text-sm rounded bg-indigo-100 text-indigo-700 hover:bg-indigo-200 disabled:opacity-50 whitespace-nowrap"
            >
              {generatingReport === t.id ? "Generating..." : "📊 Report"}
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

