import React, { useEffect, useState } from "react";
import { apiFetchJson, apiPostJson } from "../lib/utils/api";
import MAGNUS_COLORS from "../styles/magnus-colors";

/* =========================
   Types
========================= */

export interface Trend {
  id: string;
  country: string;
  category: string;
  count: number;
  highest_severity: "critical" | "warning" | "caution" | "informative";
  last_seen_at: string;
  alert_ids?: string[];
}

export interface SituationalReport {
  id: string;
  trendId: string;
  title: string;
  country: string;
  severity: string;
  content: string;
  generatedAt: string;
  metadata: any;
  html?: string;
}

/* =========================
   Helpers
========================= */

const SEVERITY_ORDER: Record<string, number> = {
  critical: 4,
  warning: 3,
  caution: 2,
  informative: 1,
};

const SEVERITY_COLOR: Record<string, string> = {
  critical: MAGNUS_COLORS.critical,
  warning: MAGNUS_COLORS.warning,
  caution: MAGNUS_COLORS.caution,
  informative: MAGNUS_COLORS.informative,
};

/* =========================
   Component
========================= */
export default function TrendsView({
  accessToken,
}: {
  accessToken?: string;
}) {
  const [trends, setTrends] = useState<Trend[]>([]);
  const [loading, setLoading] = useState(true);
  const [rebuilding, setRebuilding] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expandedTrendId, setExpandedTrendId] = useState<string | null>(null);
  const [generatingReport, setGeneratingReport] = useState<string | null>(null);
  const [report, setReport] = useState<SituationalReport | null>(null);

  const loadTrends = async () => {
    if (!accessToken) return;

    try {
      setLoading(true);
      setError(null);

      const res = await apiFetchJson<{ ok: boolean; trends?: Trend[] }>(
        "/trends",
        accessToken
      );

      if (!res?.ok) throw new Error("Failed to fetch trends");

      const sorted =
        (res.trends ?? [])
          .slice()
          .sort(
            (a, b) =>
              (SEVERITY_ORDER[b.highest_severity] ?? 0) -
              (SEVERITY_ORDER[a.highest_severity] ?? 0)
          );

      setTrends(sorted);
    } catch (e: any) {
      setError(e?.message || "Failed to load trends");
      setTrends([]);
    } finally {
      setLoading(false);
    }
  };

  const rebuildTrends = async () => {
    if (!accessToken) return;

    try {
      setLoading(true);
      setError(null);

      await apiFetchJson("/trends/rebuild", accessToken, {
        method: "POST",
      });

      await loadTrends();
    } catch (e: any) {
      setError(e?.message || "Failed to rebuild trends");
    } finally {
      setLoading(false);
    }
  };

  const generateReport = async (trendId: string) => {
    if (!accessToken) return;

    try {
      setGeneratingReport(trendId);
      setError(null);

      const res = await apiPostJson<{ ok: boolean; report?: SituationalReport; error?: string }>(
        `/trends/${trendId}/generate-report`,
        accessToken
      );

      if (!res?.ok || !res.report) {
        throw new Error(res?.error || "Failed to generate report");
      }

      setReport(res.report);
    } catch (e: any) {
      setError(e?.message || "Failed to generate report");
    } finally {
      setGeneratingReport(null);
    }
  };

  const exportReportAsText = () => {
    if (!report) return;

    // Use HTML if available, otherwise fallback to text
    const isHTML = report.html && report.html.includes('<!DOCTYPE');
    
    if (isHTML) {
      // Export as styled HTML file
      const blob = new Blob([report.html], { type: "text/html;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `MAGNUS-Report-${report.country}-${new Date().toISOString().split("T")[0]}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else {
      // Fallback to text export
      const text = `
================================================================================
                    MAGNUS TRAVEL SAFETY INTELLIGENCE
                          SITUATIONAL REPORT
================================================================================

TITLE: ${report.title}
COUNTRY: ${report.country}
SEVERITY: ${report.severity.toUpperCase()}
GENERATED: ${new Date(report.generatedAt).toLocaleString()}

================================================================================

${report.content}

================================================================================
Report ID: ${report.id}
Trend ID: ${report.trendId}
Generated by MAGNUS Intelligence System
================================================================================
    `.trim();

      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `MAGNUS-Report-${report.country}-${new Date().toISOString().split("T")[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  useEffect(() => {
    loadTrends();
  }, [accessToken]);

  if (loading) return <div className="p-4">Loading trends…</div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold" style={{ color: MAGNUS_COLORS.darkGreen }}>Trends</h2>

        <button
          onClick={rebuildTrends}
          disabled={rebuilding}
          className="px-3 py-1.5 text-sm rounded text-white hover:opacity-90 disabled:opacity-50"
          style={{ backgroundColor: MAGNUS_COLORS.deepGreen }}
        >
          {rebuilding ? "Rebuilding..." : "Rebuild Trends"}
        </button>
      </div>

      {error && <div className="text-sm" style={{ color: MAGNUS_COLORS.critical }}>{error}</div>}

      {report && (
        <div className="p-4 rounded shadow-md" style={{ backgroundColor: MAGNUS_COLORS.offWhite, borderLeft: `4px solid ${MAGNUS_COLORS.deepGreen}` }}>
          <div className="flex items-start justify-between mb-3">
            <div>
              <h3 className="font-bold" style={{ color: MAGNUS_COLORS.darkGreen }}>{report.title}</h3>
              <p className="text-xs" style={{ color: MAGNUS_COLORS.secondaryText }}>
                Generated: {new Date(report.generatedAt).toLocaleString()}
              </p>
            </div>
            <button
              onClick={() => setReport(null)}
              className="text-lg hover:opacity-80"
              style={{ color: MAGNUS_COLORS.deepGreen }}
            >
              ✕
            </button>
          </div>
          <div className="p-3 rounded mb-3 text-sm max-h-96 overflow-y-auto whitespace-pre-wrap bg-white" style={{ color: MAGNUS_COLORS.secondaryText }}>
            {report.content}
          </div>
          <button
            onClick={exportReportAsText}
            className="px-3 py-1.5 text-sm rounded text-white hover:opacity-90"
            style={{ backgroundColor: MAGNUS_COLORS.deepGreen }}
          >
            📥 Export as HTML
          </button>
        </div>
      )}

      {!trends.length && (
        <div className="p-4 text-gray-500">
          No trends detected (≥ 3 alerts in last 14 days)
        </div>
      )}

      {trends.map((t) => (
        <div
          key={t.id}
          className="border rounded p-4 bg-white shadow-sm"
          style={{ borderColor: MAGNUS_COLORS.border }}
        >
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <div className="font-semibold" style={{ color: MAGNUS_COLORS.darkGreen }}>
                {t.country} — {t.category}
              </div>
              <div className="text-sm" style={{ color: MAGNUS_COLORS.secondaryText }}>
                {t.count} alerts · highest severity {t.highest_severity}
              </div>
              <div className="text-xs" style={{ color: MAGNUS_COLORS.tertiaryText }}>
                Last seen: {new Date(t.last_seen_at).toLocaleString()}
              </div>
            </div>
            <button
              onClick={() => generateReport(t.id)}
              disabled={generatingReport === t.id}
              className="ml-3 px-3 py-1.5 text-sm rounded hover:opacity-90 disabled:opacity-50 whitespace-nowrap"
              style={{ 
                backgroundColor: MAGNUS_COLORS.offWhite, 
                color: MAGNUS_COLORS.deepGreen,
                borderColor: MAGNUS_COLORS.deepGreen,
                border: `1px solid ${MAGNUS_COLORS.deepGreen}`
              }}
            >
              {generatingReport === t.id ? "Generating..." : "📊 Report"}
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

