-- Reddit RSS Feed Sources for Travel Alerts (DEPRECATED)
-- This migration is deprecated - the sources are now managed separately
-- The "query" column no longer exists in the sources table
-- Keeping this file for migration history purposes only
