import { CSSProperties } from 'react';
import { colors } from './inline';

// Typography System - MAGNUS Brand
export const typography = {
  h1: {
    fontSize: '2rem',
    fontWeight: '800' as const,
    color: colors.magnusDarkGreen,
    marginBottom: '1rem',
    letterSpacing: '-0.025em' as const,
    textTransform: 'uppercase' as const,
  },
  h2: {
    fontSize: '1.5rem',
    fontWeight: '700' as const,
    color: colors.magnusDarkGreen,
    marginBottom: '0.75rem',
    letterSpacing: '-0.025em' as const,
  },
  h3: {
    fontSize: '1.25rem',
    fontWeight: '700' as const,
    color: colors.magnusDarkGreen,
    marginBottom: '0.5rem',
    letterSpacing: '-0.025em' as const,
  },
  h4: {
    fontSize: '1rem',
    fontWeight: '700' as const,
    color: colors.magnusDarkText,
    marginBottom: '0.5rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  },
  body: {
    fontSize: '1rem',
    color: colors.magnusDarkText,
    lineHeight: '1.6',
    fontWeight: '500' as const,
  },
  small: {
    fontSize: '0.875rem',
    color: colors.slate600,
    lineHeight: '1.5',
    fontWeight: '500' as const,
  },
  label: {
    fontSize: '0.8125rem',
    fontWeight: '700' as const,
    color: colors.magnusDarkText,
    marginBottom: '0.375rem',
    display: 'block' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  },
};

// Card Variants - MAGNUS Brand
export const cards = {
  base: {
    backgroundColor: colors.white,
    border: `1px solid ${colors.gray200}`,
    borderRadius: '12px',
    padding: '1.5rem',
    boxShadow: '0 2px 4px rgba(26, 38, 34, 0.1)',
  } as CSSProperties,
  hover: {
    backgroundColor: colors.white,
    border: `2px solid ${colors.magnusDarkGreen}`,
    borderRadius: '12px',
    padding: '1.5rem',
    boxShadow: '0 4px 8px rgba(26, 38, 34, 0.15)',
    transition: 'all 0.2s',
    cursor: 'pointer',
  } as CSSProperties,
  blue: {
    backgroundColor: colors.green50,
    border: `2px solid ${colors.magnusDarkGreen}`,
    borderRadius: '12px',
    padding: '1.5rem',
  } as CSSProperties,
  green: {
    backgroundColor: colors.green50,
    border: `2px solid ${colors.magnusAccentGreen}`,
    borderRadius: '12px',
    padding: '1.5rem',
  } as CSSProperties,
  orange: {
    backgroundColor: colors.orange50,
    border: `2px solid ${colors.magnusOrange}`,
    borderRadius: '12px',
    padding: '1.5rem',
  } as CSSProperties,
  red: {
    backgroundColor: colors.red50,
    border: `2px solid ${colors.red600}`,
    borderRadius: '12px',
    padding: '1.5rem',
  } as CSSProperties,
};

// Button Variants - MAGNUS Brand
export const buttons = {
  primary: {
    background: `linear-gradient(135deg, ${colors.magnusDarkGreen} 0%, ${colors.magnusAccentGreen} 100%)`,
    color: colors.magnusLightBg,
    border: 'none',
    borderRadius: '8px',
    padding: '0.625rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 4px 6px -1px rgba(26, 66, 52, 0.3)',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    gap: '0.5rem',
  } as CSSProperties,
  secondary: {
    backgroundColor: colors.white,
    color: colors.magnusOrange,
    border: `2px solid ${colors.magnusOrange}`,
    borderRadius: '8px',
    padding: '0.625rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    gap: '0.5rem',
  } as CSSProperties,
  ghost: {
    backgroundColor: 'transparent',
    color: colors.magnusDarkText,
    border: `1px solid ${colors.gray300}`,
    borderRadius: '8px',
    padding: '0.625rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: '600' as const,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    gap: '0.5rem',
  } as CSSProperties,
  danger: {
    backgroundColor: colors.red600,
    color: colors.white,
    border: 'none',
    borderRadius: '8px',
    padding: '0.625rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    gap: '0.5rem',
  } as CSSProperties,
  success: {
    backgroundColor: colors.magnusAccentGreen,
    color: colors.white,
    border: 'none',
    borderRadius: '8px',
    padding: '0.625rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    gap: '0.5rem',
  } as CSSProperties,
  icon: {
    backgroundColor: 'transparent',
    color: colors.slate600,
    border: 'none',
    padding: '0.5rem',
    cursor: 'pointer',
    borderRadius: '8px',
    transition: 'all 0.2s',
    display: 'inline-flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  } as CSSProperties,
  small: {
    padding: '0.5rem 1rem',
    fontSize: '0.75rem',
  } as CSSProperties,
  large: {
    padding: '0.875rem 1.75rem',
    fontSize: '1rem',
  } as CSSProperties,
};

// Form Controls - MAGNUS Brand
export const forms = {
  input: {
    width: '100%',
    padding: '0.625rem 0.875rem',
    borderRadius: '8px',
    border: `1px solid ${colors.gray300}`,
    fontSize: '0.875rem',
    fontWeight: '500' as const,
    outline: 'none',
    transition: 'all 0.2s',
    backgroundColor: colors.white,
  } as CSSProperties,
  inputFocused: {
    borderColor: colors.magnusDarkGreen,
    boxShadow: `0 0 0 3px rgba(26, 66, 52, 0.1)`,
  } as CSSProperties,
  textarea: {
    width: '100%',
    padding: '0.625rem 0.875rem',
    borderRadius: '8px',
    border: `1px solid ${colors.gray300}`,
    fontSize: '0.875rem',
    fontWeight: '500' as const,
    outline: 'none',
    minHeight: '120px',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    transition: 'all 0.2s',
  } as CSSProperties,
  select: {
    width: '100%',
    padding: '0.625rem 0.875rem',
    borderRadius: '8px',
    border: `1px solid ${colors.gray300}`,
    fontSize: '0.875rem',
    fontWeight: '600' as const,
    outline: 'none',
    backgroundColor: colors.white,
    cursor: 'pointer',
  } as CSSProperties,
  label: {
    fontSize: '0.8125rem',
    fontWeight: '700' as const,
    color: colors.magnusDarkText,
    marginBottom: '0.375rem',
    display: 'block' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
};

// Badge Variants - MAGNUS Brand
export const badges = {
  default: {
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
    display: 'inline-block' as const,
  } as CSSProperties,
  primary: {
    backgroundColor: colors.magnusDarkGreen,
    color: colors.magnusLightBg,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  secondary: {
    backgroundColor: colors.magnusOrange,
    color: colors.white,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  success: {
    backgroundColor: colors.magnusAccentGreen,
    color: colors.white,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  danger: {
    backgroundColor: colors.red600,
    color: colors.white,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  warning: {
    backgroundColor: colors.orange200,
    color: colors.magnusDarkText,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  outline: {
    backgroundColor: 'transparent',
    color: colors.magnusDarkText,
    border: `1px solid ${colors.gray300}`,
    padding: '0.375rem 0.75rem',
    borderRadius: '6px',
    fontSize: '0.75rem',
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em' as const,
  } as CSSProperties,
  // Severity-specific badges for alerts
  severity: {
    critical: {
      backgroundColor: '#dc2626',
      color: colors.white,
      padding: '0.375rem 0.75rem',
      borderRadius: '6px',
      fontSize: '0.75rem',
      fontWeight: '700' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em' as const,
    } as CSSProperties,
    warning: {
      backgroundColor: '#f59e0b',
      color: colors.white,
      padding: '0.375rem 0.75rem',
      borderRadius: '6px',
      fontSize: '0.75rem',
      fontWeight: '700' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em' as const,
    } as CSSProperties,
    caution: {
      backgroundColor: '#eab308',
      color: colors.magnusDarkText,
      padding: '0.375rem 0.75rem',
      borderRadius: '6px',
      fontSize: '0.75rem',
      fontWeight: '700' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em' as const,
    } as CSSProperties,
    informative: {
      backgroundColor: '#3b82f6',
      color: colors.white,
      padding: '0.375rem 0.75rem',
      borderRadius: '6px',
      fontSize: '0.75rem',
      fontWeight: '700' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em' as const,
    } as CSSProperties,
  },
};

// Alert Variants - MAGNUS Brand
export const alerts = {
  info: {
    backgroundColor: colors.green50,
    border: `2px solid ${colors.magnusDarkGreen}`,
    borderRadius: '8px',
    padding: '1rem',
    display: 'flex' as const,
    alignItems: 'flex-start' as const,
    gap: '0.75rem',
    color: colors.magnusDarkText,
    fontWeight: '600' as const,
  } as CSSProperties,
  success: {
    backgroundColor: colors.green50,
    border: `2px solid ${colors.magnusAccentGreen}`,
    borderRadius: '8px',
    padding: '1rem',
    display: 'flex' as const,
    alignItems: 'flex-start' as const,
    gap: '0.75rem',
    color: colors.magnusDarkText,
    fontWeight: '600' as const,
  } as CSSProperties,
  warning: {
    backgroundColor: colors.orange50,
    border: `2px solid ${colors.magnusOrange}`,
    borderRadius: '8px',
    padding: '1rem',
    display: 'flex' as const,
    alignItems: 'flex-start' as const,
    gap: '0.75rem',
    color: colors.magnusDarkText,
    fontWeight: '600' as const,
  } as CSSProperties,
  danger: {
    backgroundColor: colors.red50,
    border: `2px solid ${colors.red600}`,
    borderRadius: '8px',
    padding: '1rem',
    display: 'flex' as const,
    alignItems: 'flex-start' as const,
    gap: '0.75rem',
    color: colors.magnusDarkText,
    fontWeight: '600' as const,
  } as CSSProperties,
};

// Layout System
export const layout = {
  container: {
    maxWidth: '1280px',
    marginLeft: 'auto' as const,
    marginRight: 'auto' as const,
    paddingLeft: '1rem',
    paddingRight: '1rem',
  } as CSSProperties,
  section: {
    paddingTop: '2rem',
    paddingBottom: '2rem',
  } as CSSProperties,
  grid2: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
  } as CSSProperties,
  grid3: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
  } as CSSProperties,
  stack: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '1rem',
  } as CSSProperties,
  row: {
    display: 'flex' as const,
    flexDirection: 'row' as const,
    gap: '1rem',
    alignItems: 'center' as const,
  } as CSSProperties,
};

// Utility function to merge styles
export const merge = (...styles: CSSProperties[]): CSSProperties => {
  return Object.assign({}, ...styles);
};

// Re-export colors for convenience
export { colors } from './inline';




