import { colors } from './inline';
// Typography System - MAGNUS Brand
export const typography = {
    h1: {
        fontSize: '2rem',
        fontWeight: '800',
        color: colors.magnusDarkGreen,
        marginBottom: '1rem',
        letterSpacing: '-0.025em',
        textTransform: 'uppercase',
    },
    h2: {
        fontSize: '1.5rem',
        fontWeight: '700',
        color: colors.magnusDarkGreen,
        marginBottom: '0.75rem',
        letterSpacing: '-0.025em',
    },
    h3: {
        fontSize: '1.25rem',
        fontWeight: '700',
        color: colors.magnusDarkGreen,
        marginBottom: '0.5rem',
        letterSpacing: '-0.025em',
    },
    h4: {
        fontSize: '1rem',
        fontWeight: '700',
        color: colors.magnusDarkText,
        marginBottom: '0.5rem',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    body: {
        fontSize: '1rem',
        color: colors.magnusDarkText,
        lineHeight: '1.6',
        fontWeight: '500',
    },
    small: {
        fontSize: '0.875rem',
        color: colors.slate600,
        lineHeight: '1.5',
        fontWeight: '500',
    },
    label: {
        fontSize: '0.8125rem',
        fontWeight: '700',
        color: colors.magnusDarkText,
        marginBottom: '0.375rem',
        display: 'block',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
};
// Card Variants - MAGNUS Brand
export const cards = {
    base: {
        backgroundColor: colors.white,
        border: `1px solid ${colors.gray200}`,
        borderRadius: '12px',
        padding: '1.5rem',
        boxShadow: '0 2px 4px rgba(26, 38, 34, 0.1)',
    },
    hover: {
        backgroundColor: colors.white,
        border: `2px solid ${colors.magnusDarkGreen}`,
        borderRadius: '12px',
        padding: '1.5rem',
        boxShadow: '0 4px 8px rgba(26, 38, 34, 0.15)',
        transition: 'all 0.2s',
        cursor: 'pointer',
    },
    blue: {
        backgroundColor: colors.green50,
        border: `2px solid ${colors.magnusDarkGreen}`,
        borderRadius: '12px',
        padding: '1.5rem',
    },
    green: {
        backgroundColor: colors.green50,
        border: `2px solid ${colors.magnusAccentGreen}`,
        borderRadius: '12px',
        padding: '1.5rem',
    },
    orange: {
        backgroundColor: colors.orange50,
        border: `2px solid ${colors.magnusOrange}`,
        borderRadius: '12px',
        padding: '1.5rem',
    },
    red: {
        backgroundColor: colors.red50,
        border: `2px solid ${colors.red600}`,
        borderRadius: '12px',
        padding: '1.5rem',
    },
};
// Button Variants - MAGNUS Brand
export const buttons = {
    primary: {
        background: `linear-gradient(135deg, ${colors.magnusDarkGreen} 0%, ${colors.magnusAccentGreen} 100%)`,
        color: colors.magnusLightBg,
        border: 'none',
        borderRadius: '8px',
        padding: '0.625rem 1.25rem',
        fontSize: '0.875rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: '0 4px 6px -1px rgba(26, 66, 52, 0.3)',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    secondary: {
        backgroundColor: colors.white,
        color: colors.magnusOrange,
        border: `2px solid ${colors.magnusOrange}`,
        borderRadius: '8px',
        padding: '0.625rem 1.25rem',
        fontSize: '0.875rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    ghost: {
        backgroundColor: 'transparent',
        color: colors.magnusDarkText,
        border: `1px solid ${colors.gray300}`,
        borderRadius: '8px',
        padding: '0.625rem 1.25rem',
        fontSize: '0.875rem',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    danger: {
        backgroundColor: colors.red600,
        color: colors.white,
        border: 'none',
        borderRadius: '8px',
        padding: '0.625rem 1.25rem',
        fontSize: '0.875rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    success: {
        backgroundColor: colors.magnusAccentGreen,
        color: colors.white,
        border: 'none',
        borderRadius: '8px',
        padding: '0.625rem 1.25rem',
        fontSize: '0.875rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    icon: {
        backgroundColor: 'transparent',
        color: colors.slate600,
        border: 'none',
        padding: '0.5rem',
        cursor: 'pointer',
        borderRadius: '8px',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    small: {
        padding: '0.5rem 1rem',
        fontSize: '0.75rem',
    },
    large: {
        padding: '0.875rem 1.75rem',
        fontSize: '1rem',
    },
};
// Form Controls - MAGNUS Brand
export const forms = {
    input: {
        width: '100%',
        padding: '0.625rem 0.875rem',
        borderRadius: '8px',
        border: `1px solid ${colors.gray300}`,
        fontSize: '0.875rem',
        fontWeight: '500',
        outline: 'none',
        transition: 'all 0.2s',
        backgroundColor: colors.white,
    },
    inputFocused: {
        borderColor: colors.magnusDarkGreen,
        boxShadow: `0 0 0 3px rgba(26, 66, 52, 0.1)`,
    },
    textarea: {
        width: '100%',
        padding: '0.625rem 0.875rem',
        borderRadius: '8px',
        border: `1px solid ${colors.gray300}`,
        fontSize: '0.875rem',
        fontWeight: '500',
        outline: 'none',
        minHeight: '120px',
        fontFamily: 'inherit',
        resize: 'vertical',
        transition: 'all 0.2s',
    },
    select: {
        width: '100%',
        padding: '0.625rem 0.875rem',
        borderRadius: '8px',
        border: `1px solid ${colors.gray300}`,
        fontSize: '0.875rem',
        fontWeight: '600',
        outline: 'none',
        backgroundColor: colors.white,
        cursor: 'pointer',
    },
    label: {
        fontSize: '0.8125rem',
        fontWeight: '700',
        color: colors.magnusDarkText,
        marginBottom: '0.375rem',
        display: 'block',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
};
// Badge Variants - MAGNUS Brand
export const badges = {
    default: {
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        display: 'inline-block',
    },
    primary: {
        backgroundColor: colors.magnusDarkGreen,
        color: colors.magnusLightBg,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    secondary: {
        backgroundColor: colors.magnusOrange,
        color: colors.white,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    success: {
        backgroundColor: colors.magnusAccentGreen,
        color: colors.white,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    danger: {
        backgroundColor: colors.red600,
        color: colors.white,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    warning: {
        backgroundColor: colors.orange200,
        color: colors.magnusDarkText,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    outline: {
        backgroundColor: 'transparent',
        color: colors.magnusDarkText,
        border: `1px solid ${colors.gray300}`,
        padding: '0.375rem 0.75rem',
        borderRadius: '6px',
        fontSize: '0.75rem',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    // Severity-specific badges for alerts
    severity: {
        critical: {
            backgroundColor: '#dc2626',
            color: colors.white,
            padding: '0.375rem 0.75rem',
            borderRadius: '6px',
            fontSize: '0.75rem',
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
        },
        warning: {
            backgroundColor: '#f59e0b',
            color: colors.white,
            padding: '0.375rem 0.75rem',
            borderRadius: '6px',
            fontSize: '0.75rem',
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
        },
        caution: {
            backgroundColor: '#eab308',
            color: colors.magnusDarkText,
            padding: '0.375rem 0.75rem',
            borderRadius: '6px',
            fontSize: '0.75rem',
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
        },
        informative: {
            backgroundColor: '#3b82f6',
            color: colors.white,
            padding: '0.375rem 0.75rem',
            borderRadius: '6px',
            fontSize: '0.75rem',
            fontWeight: '700',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
        },
    },
};
// Alert Variants - MAGNUS Brand
export const alerts = {
    info: {
        backgroundColor: colors.green50,
        border: `2px solid ${colors.magnusDarkGreen}`,
        borderRadius: '8px',
        padding: '1rem',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
        color: colors.magnusDarkText,
        fontWeight: '600',
    },
    success: {
        backgroundColor: colors.green50,
        border: `2px solid ${colors.magnusAccentGreen}`,
        borderRadius: '8px',
        padding: '1rem',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
        color: colors.magnusDarkText,
        fontWeight: '600',
    },
    warning: {
        backgroundColor: colors.orange50,
        border: `2px solid ${colors.magnusOrange}`,
        borderRadius: '8px',
        padding: '1rem',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
        color: colors.magnusDarkText,
        fontWeight: '600',
    },
    danger: {
        backgroundColor: colors.red50,
        border: `2px solid ${colors.red600}`,
        borderRadius: '8px',
        padding: '1rem',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.75rem',
        color: colors.magnusDarkText,
        fontWeight: '600',
    },
};
// Layout System
export const layout = {
    container: {
        maxWidth: '1280px',
        marginLeft: 'auto',
        marginRight: 'auto',
        paddingLeft: '1rem',
        paddingRight: '1rem',
    },
    section: {
        paddingTop: '2rem',
        paddingBottom: '2rem',
    },
    grid2: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
        gap: '1.5rem',
    },
    grid3: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '1.5rem',
    },
    stack: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    row: {
        display: 'flex',
        flexDirection: 'row',
        gap: '1rem',
        alignItems: 'center',
    },
};
// Utility function to merge styles
export const merge = (...styles) => {
    return Object.assign({}, ...styles);
};
// Re-export colors for convenience
export { colors } from './inline';
